import Head from 'next/head';
import Image from 'next/image';
import svgTail from '../assets/tailwind.svg';
import Progress from '../components/Progress';
import Backlog from '../components/Backlog';
import Header from '../components/Header';
import Sidebar from '../components/Sidebar';

export default function Home() {
  return (
    <div className="h-screen">
      <Head>
        <title>Kanban-Board</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="h-screen flex">
        <div className="w-64 px-8 py-4 bg-gray-100 text-sm font-medium text-gray-900 border-r">
          <Image
            className=" rounded-full bg-gray-200 "
            width={50}
            height={50}
            src={svgTail}
            alt="tailwind"
          />
          <Sidebar />
        </div>
        <div className="flex-1 min-w-0 bg-white ">
          <div className="border-b-2 border-gray-200 ">
            <Header />
          </div>
          <div className="flex h-5/6 ">
            <Backlog />
            <Progress />
            <Progress />
          </div>
        </div>
      </div>
    </div>
  );
}
